# Generated by Django 3.0.6 on 2020-05-11 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('corparation', models.CharField(max_length=100, verbose_name='Организация')),
                ('annotation', models.TextField(verbose_name='Аннотация')),
                ('moneys', models.TextField(verbose_name='Маржа')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='MyLessons',
        ),
    ]
