# Generated by Django 3.0.6 on 2020-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200511_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceo',
            name='annotation',
            field=models.TextField(default='', verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='corparation',
            field=models.CharField(default='', max_length=100, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='moneys',
            field=models.TextField(default='', verbose_name='Маржа'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
    ]
